# Generated by Django 2.1.7 on 2019-05-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poke_Number', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Type1', models.IntegerField(default=0)),
                ('Type2', models.IntegerField(default=0)),
                ('HP', models.IntegerField(default=0)),
                ('Attack', models.IntegerField(default=0)),
                ('Defence', models.IntegerField(default=0)),
                ('SPAttack', models.IntegerField(default=0)),
                ('SPDefence', models.IntegerField(default=0)),
                ('Speed', models.IntegerField(default=0)),
                ('Generation', models.IntegerField(default=1)),
                ('Legendary', models.BooleanField(default=False)),
            ],
        ),
    ]
