# Generated by Django 2.1.7 on 2019-05-31 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LifeOfReillyJohnApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['Poke_Number']},
        ),
    ]
