# Generated by Django 2.1.7 on 2019-05-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LifeOfReillyJohnApp', '0003_auto_20190531_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='Poke_Number',
            field=models.IntegerField(),
        ),
    ]
